### PR TITLE
added @coco

### PR DESCRIPTION
**Pull request by jdknezek**
I added a `coco` function, modeled after CoffeeKup's `coffeescript` method, which serializes a function and its arguments:

```
    $ coco -es
    console.log (require \ckup .render ->
      scope =
        a: 4
        b: 2

      @script type: \text/javascript, @coco scope, ({a, b}: scope) ->
        c = ^scope
        console.log a, b, c
    )

    <script type="text/javascript"
    >;var __clone = function(it){
      function fun(){} fun.prototype = it;
      return new fun;
    };(function (scope){
        var a, b, c;
        a = scope.a, b = scope.b;
        c = __clone(scope);
        return console.log(a, b, c);
      }).apply(this, [{"a":4,"b":2}]);</script>
```

I've found this very useful for bootstrapping data into a ckup view.  The commit could be smaller (and safer) if `coco` were modified to export its `UTILITIES` somehow.

### CODE REVIEW

**Comment by satyr** [comment]
I don't like this because it:
- relies on `Function::toString` which is non-standard and unreliable in some engines.
- embeds `UTILITIES`,
  - making it vulnerable to Coco changes.
  - but doesn't take care of other scope-dependent compilations *****.

***** e.g.:

```
$ coco -sp
'' + -> a?

function (){
  return typeof a != 'undefined' && a !== null;
}

$ coco -sp
a = 1
'' + -> a?

function (){
  return a != null;
}
```

**Comment by jdknezek** [comment]
- The [ECMAScript spec](http://bclary.com/2004/11/07/#a-15.3.4.2) states that the return value of `Function.prototype.toString()` "has the syntax of a _FunctionDeclaration_", so engines that fail at this aren't spec-compliant. What's your criteria for support?
- I agree, the best solution would be if Coco exported `UTILITIES` somewhere under the `ast` object.
- Good point about other scope-dependent compilations, but the intended purpose is for simple data embedding, not complex code. This is a similar approach taken by other template engines ([CoffeeKup](https://github.com/mauricemach/coffeekup/blob/master/src/coffeekup.coffee#L241), [ck](https://github.com/aeosynth/ck/blob/master/lib/ck.coffee#L61)).

Would you prefer a method specifically for embedding data? e.g.

```
$ coco -sp
a =
  b: 4
  c: 2

d = \hello

require \ckup .render -> @embed {a, d}

<script type="text/javascript"
>this.a = {"b":4,"c":2};
this.d = "hello";</script>
```

**Comment by satyr** [comment]
Uh yes, _non-standard_ was incorrect (must be confused with `.name` there).

> the return value of `Function.prototype.toString()` "has the syntax of a _FunctionDeclaration_"

This only ensures that it takes the form `function name() { ... }` *****. The content of `...` is implementation-dependent.

For instance SpiderMonkey's `Function::toString` is pretty buggy due to bytecode decompilation:

```
js> (function(){ var a, [b] = []  })
(function () {var a, var [b] = [];})
```

*****: Even this part only is hard to be compliant, since FD can't be anonymous. `(function(){}).toString()` doesn't return _the syntax of FD_ in most engines.

> the intended purpose is for simple data embedding, not complex code

Then you should embed data only:

```
$ ckup -s
  a = b:4 c:2
  @script "data = #{ JSON.stringify a }"
  @script src: \complex-code.js

<script
>data = {"b":4,"c":2}</script><script src="complex-code.js"
></script>
```

**Comment by jdknezek** [comment]
Yes, that will work.  I was trying to avoid unchecked code.

**Pull request closed without merging**
